services:
  localstack:
    build: ./localstack
    container_name: localstack
    ports:
      - "4566:4566" # LocalStack entry point
      - "4510-4559:4510-4559" # Lambda ports
    environment:
      SERVICES: sqs,sns,lambda,iam,logs
      LAMBDA_EXECUTOR: docker
      DEBUG: 1
      DATA_DIR: /tmp/localstack/data
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      LOCALSTACK_URL: ${LOCALSTACK_URL}
    healthcheck:
      test: nc -z 127.0.0.1 4566
      interval: "5s"
      timeout: "5s"
      start_period: "10s"
      retries: 3
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock" # Required for Lambda Docker execution
  
  setup-localstack:
    build: ./setup-localstack
    container_name: setup-localstack
    environment:
      LOCALSTACK_URL: ${LOCALSTACK_URL}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      localstack:
        condition: service_healthy
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  localstack_data: