services:
  localstack:
    build: ./localstack
    container_name: localstack
    ports:
      - "4566:4566" # LocalStack entry point
      - "4510-4559:4510-4559" # Lambda ports
    environment:
      - SERVICES=sqs,sns,lambda,iam
      - LAMBDA_EXECUTOR=docker
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - LOCALSTACK_URL=${LOCALSTACK_URL}
    volumes:
      - "./localstack/src:/etc/localstack/init/ready.d" # Initialization scripts
      - "/var/run/docker.sock:/var/run/docker.sock" # Required for Lambda Docker execution
